// Generated by CoffeeScript 1.3.3
(function() {
  var TitleView, exports, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TitleView = (function(_super) {

    __extends(TitleView, _super);

    function TitleView() {
      this.render = __bind(this.render, this);
      return TitleView.__super__.constructor.apply(this, arguments);
    }

    TitleView.prototype.className = 'jmbo-title-view';

    TitleView.prototype.initialize = function() {};

    TitleView.prototype.render = function() {
      this.$el.html(this.options.name);
      if (this.options.actionLeft != null) {
        this.$el.append("LEFTY");
      }
      if (this.options.actionRight != null) {
        this.$el.append("RIGHTY");
      }
      return this;
    };

    return TitleView;

  })(Backbone.View);

  exports = this;

  exports.Jmbo = (_ref = exports.Jmbo) != null ? _ref : {};

  exports.Jmbo.TitleView = TitleView;

}).call(this);
