// Generated by CoffeeScript 1.3.1
(function() {
  var NavigationControllerView, TabBarControllerView, TabBarView, TitleView, ViewController, ViewControllerView, ViewControllers,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  TitleView = (function(_super) {

    __extends(TitleView, _super);

    TitleView.name = 'TitleView';

    function TitleView() {
      this.setTitle = __bind(this.setTitle, this);

      this.render = __bind(this.render, this);
      return TitleView.__super__.constructor.apply(this, arguments);
    }

    TitleView.prototype.className = 'jmbo-title-view';

    TitleView.prototype.initialize = function() {
      this.template = _.template('<h1><%= title %></h1>');
      return this.title = 'Untitled';
    };

    TitleView.prototype.render = function() {
      return this.$el.html(this.template({
        title: this.title
      }));
    };

    TitleView.prototype.setTitle = function(title) {
      return this.title = title;
    };

    return TitleView;

  })(Backbone.View);

  ViewController = (function(_super) {

    __extends(ViewController, _super);

    ViewController.name = 'ViewController';

    function ViewController() {
      return ViewController.__super__.constructor.apply(this, arguments);
    }

    ViewController.prototype.defaults = {
      titleView: TitleView,
      childView: null,
      title: '',
      icon: null,
      _view: null
    };

    return ViewController;

  })(Backbone.Model);

  ViewControllers = (function(_super) {

    __extends(ViewControllers, _super);

    ViewControllers.name = 'ViewControllers';

    function ViewControllers() {
      return ViewControllers.__super__.constructor.apply(this, arguments);
    }

    ViewControllers.prototype.model = ViewController;

    return ViewControllers;

  })(Backbone.Collection);

  ViewControllerView = (function(_super) {

    __extends(ViewControllerView, _super);

    ViewControllerView.name = 'ViewControllerView';

    function ViewControllerView() {
      this.animate = __bind(this.animate, this);

      this.render = __bind(this.render, this);
      return ViewControllerView.__super__.constructor.apply(this, arguments);
    }

    ViewControllerView.prototype.className = 'jmbo-view-controller-view';

    ViewControllerView.prototype.render = function() {
      var childView, titleView;
      if (!(this.model != null)) {
        return false;
      }
      titleView = new (this.model.get('titleView'));
      titleView.setTitle(this.model.get('title'));
      this.$el.html(titleView.render());
      childView = this.model.get('childView');
      if (!(childView != null)) {
        return false;
      }
      this.$el.append(this.model.get('childView').render());
      return this.el;
    };

    ViewControllerView.prototype.animate = function(name, direction, callback) {
      return jmbo.view.animate(this.$el, name, direction, callback);
    };

    return ViewControllerView;

  })(Backbone.View);

  NavigationControllerView = (function(_super) {

    __extends(NavigationControllerView, _super);

    NavigationControllerView.name = 'NavigationControllerView';

    function NavigationControllerView() {
      this.push = __bind(this.push, this);

      this.pop = __bind(this.pop, this);

      this.render = __bind(this.render, this);
      return NavigationControllerView.__super__.constructor.apply(this, arguments);
    }

    NavigationControllerView.prototype.className = 'jmbo-view-navigation-controller-view';

    NavigationControllerView.prototype.initialize = function() {
      this.collection = null;
      return this.collection = new ViewControllers;
    };

    NavigationControllerView.prototype.render = function() {
      this.$el.html('');
      return this.el;
    };

    NavigationControllerView.prototype.pop = function(options) {
      var currentVC, currentVC_view, prevVC, prevVC_view;
      if (options == null) {
        options = {
          animation: 'slide-left'
        };
      }
      currentVC = this.collection.pop();
      if (!(currentVC != null)) {
        return null;
      }
      currentVC_view = currentVC.get('_view');
      currentVC_view.animate(options.animation, 'out', function() {
        currentVC_view.$el.html('').remove();
        return currentVC.unset('_view');
      });
      if (this.collection.length > 0) {
        prevVC = this.collection.last();
        prevVC_view = new ViewControllerView({
          model: prevVC
        });
        prevVC.set({
          _view: prevVC_view
        });
        this.$el.prepend(prevVC_view.render());
        prevVC_view.animate(options.animation, 'in');
      }
      return currentVC;
    };

    NavigationControllerView.prototype.push = function(nextVC, options) {
      var currentVC, currentVC_view, nextVC_view;
      if (options == null) {
        options = {
          animation: 'slide-right'
        };
      }
      if (this.collection.length > 0) {
        currentVC = this.collection.last();
        currentVC_view = currentVC.get('_view');
        currentVC_view.animate(options.animation, 'out', function() {
          currentVC_view.$el.html('').remove();
          return currentVC.unset('_view');
        });
      }
      this.collection.add(nextVC);
      nextVC_view = new ViewControllerView({
        model: nextVC
      });
      nextVC.set({
        _view: nextVC_view
      });
      this.$el.append(nextVC_view.render());
      nextVC_view.animate(options.animation, 'in');
      return nextVC;
    };

    return NavigationControllerView;

  })(Backbone.View);

  TabBarView = (function(_super) {

    __extends(TabBarView, _super);

    TabBarView.name = 'TabBarView';

    function TabBarView() {
      this.render = __bind(this.render, this);
      return TabBarView.__super__.constructor.apply(this, arguments);
    }

    TabBarView.prototype.className = 'jmbo-view-tab-bar-view';

    TabBarView.prototype.initialize = function() {
      this.template = _.template("<% collection.each(function(vc) { console.log(vc) %>\n  <div>1<%= vc.title %></div>\n<% }) %>");
      return this.collection.on('render add', this.render);
    };

    TabBarView.prototype.render = function() {
      l('pew');
      this.$el.html(this.template({
        collection: this.collection
      }));
      return this.el;
    };

    return TabBarView;

  })(Backbone.View);

  TabBarControllerView = (function(_super) {

    __extends(TabBarControllerView, _super);

    TabBarControllerView.name = 'TabBarControllerView';

    function TabBarControllerView() {
      this.add = __bind(this.add, this);

      this.render = __bind(this.render, this);
      return TabBarControllerView.__super__.constructor.apply(this, arguments);
    }

    TabBarControllerView.prototype.className = 'jmbo-view-tab-bar-controller-view';

    TabBarControllerView.prototype.initialize = function() {
      this.collection = null;
      return this.collection = new ViewControllers;
    };

    TabBarControllerView.prototype.render = function() {
      var tabBar;
      tabBar = new jmbo.view.TabBarView({
        collection: this.collection
      });
      this.$el.html(tabBar.render());
      return this.el;
    };

    TabBarControllerView.prototype.add = function(viewController) {
      return this.collection.add(viewController);
    };

    return TabBarControllerView;

  })(Backbone.View);

  namespace('jmbo.view', function(exports) {
    exports.Controller = ViewController;
    exports._ControllerView = ViewControllerView;
    exports.TitleView = TitleView;
    exports.NavigationControllerView = NavigationControllerView;
    exports.TabBarView = TabBarView;
    exports.TabBarControllerView = TabBarControllerView;
    return exports.animate = function($el, name, direction, callback) {
      var className;
      className = name + '-' + direction;
      $el.addClass(className);
      return $el.on('webkitAnimationEnd', function() {
        $el.removeClass(className).off('webkitAnimationEnd');
        if (callback) {
          return callback();
        }
      });
    };
  });

}).call(this);
