// Generated by CoffeeScript 1.3.1
(function() {
  var Config, Controller, ControllerView, Controllers,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Controller = (function(_super) {

    __extends(Controller, _super);

    Controller.name = 'Controller';

    function Controller() {
      return Controller.__super__.constructor.apply(this, arguments);
    }

    Controller.prototype.defaults = {
      view: null
    };

    return Controller;

  })(Backbone.Model);

  Controllers = (function(_super) {

    __extends(Controllers, _super);

    Controllers.name = 'Controllers';

    function Controllers() {
      return Controllers.__super__.constructor.apply(this, arguments);
    }

    Controllers.prototype.model = Controller;

    return Controllers;

  })(Backbone.Collection);

  Config = (function(_super) {

    __extends(Config, _super);

    Config.name = 'Config';

    function Config() {
      return Config.__super__.constructor.apply(this, arguments);
    }

    Config.prototype.defaults = {
      TitleView: jmbo.ui.TitleView,
      childView: null,
      title: 'Untitled',
      icon: null
    };

    return Config;

  })(Backbone.Model);

  ControllerView = (function(_super) {

    __extends(ControllerView, _super);

    ControllerView.name = 'ControllerView';

    function ControllerView() {
      this.animate = __bind(this.animate, this);

      this.render = __bind(this.render, this);
      return ControllerView.__super__.constructor.apply(this, arguments);
    }

    ControllerView.prototype.className = 'jmbo-ui-view-controller-view';

    ControllerView.prototype.initialize = function() {
      return this.config = new Config(this.options);
    };

    ControllerView.prototype.render = function() {
      var TitleView, childView, titleView;
      TitleView = this.config.get('TitleView');
      if (TitleView != null) {
        titleView = new TitleView;
        titleView.setTitle(this.config.get('title'));
        this.$el.html(titleView.render());
      }
      childView = this.config.get('childView');
      if (childView != null) {
        this.$el.append(childView.render());
      }
      return this.el;
    };

    ControllerView.prototype.animate = function(name, direction, callback) {
      return jmbo.ui.animate(this.$el, name, direction, callback);
    };

    return ControllerView;

  })(Backbone.View);

  namespace('jmbo.ui.view', function(exports) {
    exports.Controller = Controller;
    exports.Controllers = Controllers;
    return exports.ControllerView = ControllerView;
  });

}).call(this);
