(function(){var l,m,p,n,j,q,k,o=[].slice,e=function(b,a){return function(){return b.apply(a,arguments)}},r={}.hasOwnProperty,h=function(b,a){function i(){this.constructor=b}for(var g in a)r.call(a,g)&&(b[g]=a[g]);i.prototype=a.prototype;b.prototype=new i;b.__super__=a.prototype;return b};window.namespace=function(b,a,i){var g,d,c,f,e;3>arguments.length&&(g=["undefined"!==typeof exports?exports:window].concat(o.call(arguments)),b=g[0],a=g[1],i=g[2]);d=b;e=a.split(".");c=0;for(f=e.length;c<f;c++)g=
e[c],b=b[g]||(b[g]={});return i(b,d)};window.log=function(){var b;b=1<=arguments.length?o.call(arguments,0):[];1===b.length&&(b=b[0]);return console.log(b)};k=function(b){function a(){this.setTitle=e(this.setTitle,this);this.render=e(this.render,this);return a.__super__.constructor.apply(this,arguments)}h(a,b);a.name="TitleView";a.prototype.className="jmbo-ui-title-view";a.prototype.template=_.template("<h1><%= title %></h1>");a.prototype.initialize=function(){return this.title="Untitled"};a.prototype.render=
function(){return this.$el.html(this.template({title:this.title}))};a.prototype.setTitle=function(a){return this.title=a};return a}(Backbone.View);namespace("jmbo.ui",function(b){b.TitleView=k;return b.animate=function(a,i,g,b){var c,f;c=i+"-"+g;f="anim-event-"+c;a.addClass(c);a.on(f,function(){a.off(f);a.removeClass(c);if(b)return b()});a.on("webkitAnimationEnd animationEnd",function(){return a.trigger(f)});if(!1===i)return a.trigger(f)}});n=function(b){function a(){return a.__super__.constructor.apply(this,
arguments)}h(a,b);a.name="Controller";a.prototype.defaults={view:void 0};return a}(Backbone.Model);q=function(b){function a(){return a.__super__.constructor.apply(this,arguments)}h(a,b);a.name="Controllers";a.prototype.model=n;return a}(Backbone.Collection);p=function(b){function a(){return a.__super__.constructor.apply(this,arguments)}h(a,b);a.name="Config";a.prototype.defaults={TitleView:jmbo.ui.TitleView,view:void 0,title:"Untitled",icon:void 0};return a}(Backbone.Model);j=function(b){function a(){this.animate=
e(this.animate,this);this.firePostRenderEvent=e(this.firePostRenderEvent,this);this.render=e(this.render,this);return a.__super__.constructor.apply(this,arguments)}h(a,b);a.name="ControllerView";a.prototype.className="jmbo-ui-view-controller-view";a.prototype.initialize=function(){var a;this.config=new p(this.options);a=this.config.get("view");if(null!=a)return a.controller=this};a.prototype.render=function(){var a;this.$el.html("");k=this.config.get("TitleView");null!=k&&(null==this.titleView&&(this.titleView=
new k),this.$el.html(this.titleView.render()),this.titleView.setTitle(this.config.get("title")));a=this.config.get("view");null!=a&&(a=null!=a.render?a.render():$(a).html(),$(a).addClass("jmbo-ui-view-controller-view-view"),this.$el.append(a));return this.el};a.prototype.firePostRenderEvent=function(){var a;a=this.config.get("view");if(null!=a)return a.delegateEvents(),a.trigger("render:post")};a.prototype.animate=function(a,g,b){return jmbo.ui.animate(this.$el,a,g,b)};return a}(Backbone.View);namespace("jmbo.ui.view",
function(b){b.Controller=n;b.Controllers=q;return b.ControllerView=j});j=function(b){function a(){this.pop=e(this.pop,this);this.push=e(this.push,this);this.firePostRenderEvent=e(this.firePostRenderEvent,this);this.render=e(this.render,this);return a.__super__.constructor.apply(this,arguments)}h(a,b);a.name="ControllerView";a.prototype.className="jmbo-ui-stack-controller-view";a.prototype.initialize=function(){a.__super__.initialize.apply(this,arguments);return this.collection=new jmbo.ui.view.Controllers};
a.prototype.render=function(){var a,b,d,c;b=this.collection.where({_cache:!0});b.push(this.collection.last());this.$el.html("");if(b.length){d=0;for(c=b.length;d<c;d++)a=b[d],a=a.get("view"),this.$el.append(a.render())}return this.el};a.prototype.firePostRenderEvent=function(){var a,b,d,c,f;b=this.collection.where({_cache:!0});b.push(this.collection.last());if(b.length){f=[];d=0;for(c=b.length;d<c;d++)a=b[d],a=a.get("view"),f.push(a.firePostRenderEvent());return f}};a.prototype.push=function(a,b){var d,
c,b=_.extend({animation:"slide-right",removeFromDom:!0},b);d=this.collection.last();null!=d&&(c=d.get("view"),c.animate(b.animation,"out",function(){d.set("_cache",!b.removeFromDom);if(b.removeFromDom)return c.$el.html("").remove()}));this.collection.add({view:a});this.$el.append(a.render());a.animate(b.animation,"in",function(){a.firePostRenderEvent();if(b.callback)return b.callback()});return a};a.prototype.pop=function(a){var b,d,c,a=_.extend({animation:"slide-left"},a);b=this.collection.pop();
null!=b&&(d=b.get("view"),d.animate(a.animation,"out",function(){d.$el.html("").remove();if(a.callback)return a.callback()}));b=this.collection.last();null!=b&&(c=b.get("view"),b.get("_cache")||(this.$el.append(c.render()),c.firePostRenderEvent()),c.animate(a.animation,"in"));return d};return a}(jmbo.ui.view.ControllerView);namespace("jmbo.ui.stack",function(b){return b.ControllerView=j});l=function(b){function a(){this.renderSelected=e(this.renderSelected,this);this.render=e(this.render,this);this.select=
e(this.select,this);return a.__super__.constructor.apply(this,arguments)}h(a,b);a.name="BarItemView";a.prototype.tagName="li";a.prototype.className="jmbo-ui-tab-bar-item-view";a.prototype.events={touchstart:"select"};a.prototype.initialize=function(){return this.model.on("change:selected",this.renderSelected)};a.prototype.select=function(){var a,b,d,c,f;if(!0!==this.model.get("selected")){f=this.model.collection.where({selected:!0});b=function(){return a.set({selected:!1})};d=0;for(c=f.length;d<c;d++)a=
f[d],b();return this.model.set({selected:!0})}};a.prototype.render=function(){var a;a=this.model.get("view").config;this.$el.html(a.get("title"));a=a.get("icon");null!=a&&this.$el.append('<div class="icon-'+a+'"></div>');return this.el};a.prototype.renderSelected=function(){return this.$el.toggleClass("selected")};return a}(Backbone.View);m=function(b){function a(){this.render=e(this.render,this);return a.__super__.constructor.apply(this,arguments)}h(a,b);a.name="BarView";a.prototype.tagName="ul";
a.prototype.className="jmbo-ui-tab-bar-view";a.prototype.initialize=function(){return this.collection.on("reset",this.render)};a.prototype.render=function(){var a;this.$el.html("");a=this;this.collection.each(function(b){return a.$el.append((new l({model:b})).render())});return this.el};return a}(Backbone.View);j=function(b){function a(){this.selectedIndex=e(this.selectedIndex,this);this.set=e(this.set,this);this.renderSelected=e(this.renderSelected,this);this.render=e(this.render,this);return a.__super__.constructor.apply(this,
arguments)}h(a,b);a.name="ControllerView";a.prototype.className="jmbo-ui-tab-controller-view";a.prototype.initialize=function(){a.__super__.initialize.apply(this,arguments);this.collection=new jmbo.ui.view.Controllers;this.collection.on("change:selected",this.renderSelected);return this._selectedIndex=0};a.prototype.render=function(){this.$el.html('<div id="jmbo-ui-tab-controller-view-context"></div>');this.$el.append((new m({collection:this.collection})).render());return this.el};a.prototype.renderSelected=
function(){var a;a=this.collection.where({selected:!0});if(a.length&&(a=a[0].get("view"),null!=a))return this.$el.find("#jmbo-ui-tab-controller-view-context").html(a.render()),a.firePostRenderEvent()};a.prototype.set=function(){var a,b,d,c,f,e;a=1<=arguments.length?o.call(arguments,0):[];this.collection.reset([],{silent:!0});if(0===a.length)this.collection.trigger("reset");else{b=this;c=function(){return b.collection.add({view:d,selected:!1},{silent:!0})};f=0;for(e=a.length;f<e;f++)d=a[f],c();this.collection.trigger("reset");
return this.selectedIndex(0)}};a.prototype.selectedIndex=function(a){var b,d,c,e,h;if(null==a)return a=this._selectedIndex;h=this.collection.where({selected:!0});d=function(){return b.set({selected:!1})};c=0;for(e=h.length;c<e;c++)b=h[c],d();this.collection.at(a).set({selected:!0});return this._selectedIndex=a};return a}(jmbo.ui.view.ControllerView);namespace("jmbo.ui.tab",function(b){b.ControllerView=j;b._BarView=m;return b._BarItemView=l})}).call(this);
