// Generated by CoffeeScript 1.3.3
(function() {
  var BarItemView, BarView, TabView, TabViewVessel, TabViewVessels, exports,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __slice = [].slice,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  TabViewVessel = (function(_super) {

    __extends(TabViewVessel, _super);

    function TabViewVessel() {
      return TabViewVessel.__super__.constructor.apply(this, arguments);
    }

    TabViewVessel.prototype.defaults = {
      icon: '',
      name: 'Unnamed',
      view: void 0,
      removeFromDOM: true,
      func: void 0
    };

    return TabViewVessel;

  })(Backbone.Model);

  TabViewVessels = (function(_super) {

    __extends(TabViewVessels, _super);

    function TabViewVessels() {
      return TabViewVessels.__super__.constructor.apply(this, arguments);
    }

    TabViewVessels.prototype.model = TabViewVessel;

    return TabViewVessels;

  })(Backbone.Collection);

  TabView = (function(_super) {

    __extends(TabView, _super);

    function TabView() {
      this.selectAtIndex = __bind(this.selectAtIndex, this);

      this.removeAtIndex = __bind(this.removeAtIndex, this);

      this.reset = __bind(this.reset, this);

      this.add = __bind(this.add, this);

      this.renderSelected = __bind(this.renderSelected, this);

      this.render = __bind(this.render, this);
      return TabView.__super__.constructor.apply(this, arguments);
    }

    TabView.prototype.className = 'jmbo-tab-view';

    TabView.prototype.initialize = function() {
      if (!(this.collection != null)) {
        this.collection = new TabViewVessels;
      }
      return this.collection.on('change:selected', this.renderSelected);
    };

    TabView.prototype.render = function() {
      var selectedView;
      this.$el.contents().detach();
      this.$context = $('<div class="jmbo-tab-view-context"></div>');
      this.$el.append(this.$context);
      this.barView = new BarView({
        collection: this.collection
      });
      this.$el.append(this.barView.render().el);
      selectedView = this.collection.where({
        'selected': true
      })[0];
      if (selectedView != null) {
        this.renderSelected(selectedView);
      }
      return this;
    };

    TabView.prototype.renderSelected = function(model) {
      var view, _base, _ref;
      if (!model.get('selected')) {
        if ((_ref = model.get('view')) != null) {
          _ref.trigger('tab:blur');
        }
        return;
      }
      if (typeof (_base = model.get('func')) === "function") {
        _base();
      }
      if (model.get('removeFromDOM')) {
        this.$context.contents().detach();
      }
      view = model.get('view');
      if (view != null) {
        this.$context.append(view.render().el);
        return view.trigger('tab:focus');
      }
    };

    TabView.prototype.add = function(obj) {
      return this.collection.add(obj);
    };

    TabView.prototype.reset = function() {
      var objs;
      objs = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return this.collection.reset(objs);
    };

    TabView.prototype.removeAtIndex = function(i) {
      return this.collection.remove(this.collection.at(i));
    };

    TabView.prototype.selectAtIndex = function(i) {
      var _ref;
      if ((_ref = this.collection.where({
        selected: true
      })[0]) != null) {
        _ref.set({
          selected: false
        });
      }
      return this.collection.at(i).set({
        'selected': true
      });
    };

    return TabView;

  })(Backbone.View);

  BarView = (function(_super) {

    __extends(BarView, _super);

    function BarView() {
      this.render = __bind(this.render, this);
      return BarView.__super__.constructor.apply(this, arguments);
    }

    BarView.prototype.tagName = 'ul';

    BarView.prototype.className = 'jmbo-tab-bar-view';

    BarView.prototype.initialize = function() {
      return this.collection.on('add reset remove', this.render);
    };

    BarView.prototype.render = function() {
      var _this = this;
      this.$el.html('');
      this.collection.each(function(model) {
        return _this.$el.append(new BarItemView({
          model: model
        }).render().el);
      });
      return this;
    };

    return BarView;

  })(Backbone.View);

  BarItemView = (function(_super) {

    __extends(BarItemView, _super);

    function BarItemView() {
      this.select = __bind(this.select, this);

      this.renderSelected = __bind(this.renderSelected, this);

      this.render = __bind(this.render, this);
      return BarItemView.__super__.constructor.apply(this, arguments);
    }

    BarItemView.prototype.tagName = 'li';

    BarItemView.prototype.initialize = function() {
      var tap;
      this.model.on('change:selected', this.renderSelected);
      tap = 'click';
      if (__indexOf.call(document.documentElement, 'ontouchstart') >= 0) {
        tap = 'touchstart';
      }
      return this.$el.on(tap, this.select);
    };

    BarItemView.prototype.render = function() {
      this.$el.html(this.model.get('name')).addClass(this.model.get('icon'));
      return this;
    };

    BarItemView.prototype.renderSelected = function() {
      return this.$el.toggleClass('selected');
    };

    BarItemView.prototype.select = function() {
      var _ref;
      if (this.model.get('selected') === true) {
        return;
      }
      if ((_ref = this.model.collection.where({
        selected: true
      })[0]) != null) {
        _ref.set({
          selected: false
        });
      }
      return this.model.set({
        selected: true
      });
    };

    return BarItemView;

  })(Backbone.View);

  exports = this;

  exports.Jmbo = exports.Jmbo || {};

  exports.Jmbo.TabView = TabView;

}).call(this);
